const cards = [
  {
    type: 'settings',
  },
  {
    type: 'intro',
    name: 'Introducing Ghosts',
    desc: `A Ghost is an evil spirit of a dead person that feeds off peoples fear. They are created from violent, sudden deaths. If disturbed they can wreck havoc across neighbourhoods and they have also been known to be up to 1000 years old.\n\n This guide will help you understand what you need to do to surivive.`,
    nameRU: 'Призраки',
    descRU: `Призрак - это злой дух мёртвого человека, который питается страхом людей. Призраки рождаются в результате насильственной, преждевременной смерти. Если их потревожить, они могут сеять хаос в окрестностях на протяжении тысячелетий. \n \n Это руководство поможет вам понять, что вам нужно делать, чтобы выжить.`,
    nameES: 'Introducción a los Fantasmas',
    descES:
      'El Fantasma es un espíritu maligno de una persona muerta que se alimenta del miedo de sus víctimas. Surgen a partir de una muerte violenta y repentina. Si se les molesta pueden llegar a causar estragos en los vecindarios, se conoce que pueden llegar a atener hasta 1000 años de edad.\n\n Esta guía te ayudará a entender qué tienes que hacer para sobrevivir.',
    nameFR: `Introduction des fantômes`,
    descFR: `Un fantôme est un esprit démoniaque d'une personne morte qui se nourrit de la peur des gens. Les fantômes ne sont créé que quand la mort est violente et soudaine. Si ils sont dérangé, les fantômes peuvent causer des ennuis dans le quartier et certains sont connus pour avoir vécus plus de 1000 ans.\n\n Ce guide va vous aider à comprendre ce dont vous aurez besoin pour survivre. `,
    nameIT: `Introduzione ai Fantasmi`,
    descIT: `Un Fantasma è lo spirito maligno di una persona morta che si nutre della paura. Essi sono il frutto di morti violente e improvvise. Se disturbati possono provocare il caos nei quartieri, ed è risaputoche possono avere anche fino a 1000 anni.\n\n Questa guida ti aiuterà a capire cosa è necessario fare per sopravvivere.`,
  },
  {
    type: 'intro',
    name: 'Gathering Evidence',
    desc: `Evidence of the supernatural is high in demand which means it can sell. Hunting Ghosts however is an extremely dangerous task.\n\n It will be your job to enter locations and gather as much evidence of the supernatural as possible, just remember, don't outstay your welcome.\n\n `,
    nameRU: `Сбор доказательств`,
    descRU: `Доказательства сверхъестественного пользуются большим спросом, а значит, их можно продавать. Однако охота на призраков - чрезвычайно опасная работа. \n \n Вашей задачей будет проникать в места обитания призраков и собирать как можно больше доказательств сверхъестественного. Но не злоупотребляйте гостеприимством хозяев. \n \n`,
    nameES: `Reuniendo pruebas`,
    descES: `Hay una gran demanda de pruebas paranormales lo que hace que se compren a un precio alto. Sin embargo, cazar fantasmas es una tarea extremadamente peligrosa.\n\n Será vuestro trabajo acudir a lugares y reunir pruebas que corroboren la existencia de actividad paranormal. Pero no abuséis de la hospitalidad de vuestro anfitrión.\n\n`,
    nameFR: `Collecter les évidences`,
    descFR: `Les évidences prouvant l'existence du surnaturel sont très demandés ce qui veut dire qu'ils peuvent se vendre. Chasser des fantômes est une tâche très dangereuse.\n\n votre boulot sera de rentrer dans des lieux hantés et de trouver autant de preuve surnaturel que possible mais rappelez vous, n'abusez pas de votre accueille envers le fantôme.\n\n`,
    nameIT: `Raccolta Prove`,
    descIT: `La domanda di prove del soprannaturale è alta, significa che è possibile guadagnarci. La Caccia ai Fantasmi, tuttavia, è un'operazione estremamente pericolosa.\n\n Sarà tuo compito entrare nei luoghi e raccogliere più prove del soprannaturale possibile, ricorda, non rimanere più del dovuto.\n\n `,
  },
  {
    type: 'intro',
    name: 'Staying Alive',
    desc: `In order to discover what type of Ghost you are dealing with you will have to learn each Ghosts strengths and weaknesses.\n\nThe digital clock in the truck shows you how long you have before the Ghost will get angry and lower your sanity faster, use this time to find the Ghost and setup equipment. If your sanity becomes too low the recommended action is to leave.`,
    nameRU: `Выживание`,
    descRU: `Чтобы узнать, с каким типом Призраков вы имеете дело, вам нужно изучить сильные и слабые стороны каждого Призрака. \n \n Таймер в грузовике показывает, сколько времени у вас осталось до того, как Призрак рассердится и начнет снижать уровень вашего Рассудка сильнее. Используйте это время, чтобы найти Призрака и настроить оборудование. Если уровень Рассудка становится слишком низким - лучше уйти.`,
    nameES: `Mantenerse vivo`,
    descES: `Para descubrir con qué tipo de Fantasma estás tratando tendrás que aprender los puntos fuertes y débiles de cada uno.\n\n El reloj digital del camión te muestra cuánto tiempo tienes antes de que el Fantasma se enfade y te baje la cordura más rápido, usa este tiempo para encontrar al Fantasma y preparar el equipo. Si tu cordura se vuelve demasiado baja, lo recomendable es abandonar.`,
    nameFR: `Rester en vie`,
    descFR: `Afin de découvrir quel est le type du fantôme auquel vous avez affaire, vous devez apprendre forces et faiblesses de chaqu'un des fantômes.\n\n L'horloge digital dans votre camion vous montre combien de temps vous avez avant que le fantôme deviennent énervé et réduisent votre santé mentale encore plus rapidement que normal. Utilisez ce temps pour trouver le fantôme et préparer votre équipement. Si votre santé mentale est trop basse, il est fortement conseillé de partir. `,
    nameIT: `Rimanere in Vita`,
    descIT: `Per scoprire con quale tipo di Fantasma hai a che fare dovrai imparare ogni suo punto di forza e debolezza.\n\n L'orologio digitale nel furgone mostra quanto tempo rimane prima che il Fantasma si arrabbi e la tua Sanità Mentale cominci a calare più velocemente, utilizza questo tempo per trovare il Fantasma e posizionare l'attrezzatura. Se la tua sanità mentale si abbassa troppo l'azione consigliata è di andare via.`,
  },
  {
    type: 'intro',
    name: `A Hunter's Sanity`,
    desc: `In your investigation into the supernatural you will need to make sure your Sanity is kept high. All types of Ghosts prey on our Sanity making them stronger the more insane we become.\n\n To keep your sanity high around the paranormal make sure you stay in lit areas.\n\n `,
    nameRU: `Рассудок охотника`,
    descRU: `Во время расследования вам нужно будет следить за тем, чтобы уровень Рассудка был достаточно высок. Все виды призраков питаются нашим страхом и становятся тем сильнее, чем безумнее мы становимся. \n \n Чтобы поддерживать высокий уровень рассудка в присутствии паранормальных сил, старайтесь оставаться на свету. \n \n`,
    nameES: `Cordura`,
    descES: `Mientras investigas fenómenos paranormales debes asegurarte de que tu Cordura se mantiene alta. Los Fantasmas intentarán mermar tu Cordura haciéndolos más fuertes cuando más loco te vuelvas.\n\n Para mantener tus niveles de Cordura de manera estable, quédate en las zonas iluminadas.\n\n`,
    nameFR: `La santé mentale du chasseur de fantôme`,
    descFR: `Dans votre investigation dans le paranormal, vous aurez besoin de vous assurer que votre santé mentale est haute et le reste. Tout les types de fantômes s'attaque à notre santé mentale ce qui les rends plus forts et plus nous devenons fous. Pour garder votre santé mentale haute même entouré de paranormal, assurez vous que vous êtes dans une zone éclairée. `,
    nameIT: `Sanità Mentale del Cacciatore`,
    descIT: `Durante la tua indagine del soprannaturale è necessario assicurarsi che la Sanità Mentale rimanga alta. I Fantasmi cercheranno di sottrarre la tua Sanità Mentale diventando più forti all'aumentare della pazzia.\n\n Per mantenere la tua Sanità Mentale alta assicurati di rimanere in zone illuminate.\n\n `,
  },
  {
    type: 'ghost',
    name: 'Spirit',
    desc: `A spirit is the most common Ghost you will come across however it is still very powerful and dangerous. They are usually discovered at one of their hunting grounds after an unexplained death.`,
    strength: `Nothing`,
    weakness: `Using Smudge Sticks on a Spirit will stop it attacking for a long period of time.`,
    evidence: `EMF Level 5, Ghost Writing, Spirit Box`,
    nameRU: `Дух`,
    descRU: `Дух - наиболее распространённый вид призрака, но он тоже силён и опасен. Духов можно обнаружить там, где недавно при странных обстоятельствах погибли люди.`,
    strengthRU: `Нет`,
    weaknessRU: `Использование Благовония обезоруживает Духа на долгое время`,
    nameES: `Espíritu`,
    descES: `Un Espíritu es uno de los Fantasmas más comunes. Aun así sigue siendo muy poderoso y peligroso. Se les ha avistado en lugares donde ha ocurrido una muerte inexplicable.`,
    strengthES: `Ninguno`,
    weaknessES: `Usar Varillas de Incienso cerca de un Espíritu hará que no ataque por un largo periodo de tiempo.`,
    nameFR: `Esprit`,
    descFR: `Un esprit est le fantôme le plus commun que vous pourrez rencontrer cependant il reste très puissant et dangereux. Ils sont souvent découverts sur leur terrain de chasse après une mort inexpliqué. `,
    strengthFR: `Rien`,
    weaknessFR: `Utiliser des bâtons d'encens sur un esprit va l'empêcher d'attaquer pendant un long moment. `,
    nameIT: `Spirito`,
    descIT: `Lo Spirito è il Fantasma più comuneche troverai, tuttavia è potente e pericoloso. Di solito vengono scoperti in uno dei loro territori di caccia, dopo una morte inspiegabile.`,
    strengthIT: `Nessuno`,
    weaknessIT: `Usare l'Incenso su uno Spirito gli impediràdi attaccare per un bel po' di tempo.`,
  },
  {
    type: 'ghost',
    name: 'Wraith',
    desc: `A wraith is one of the most dangerous Ghosts you will find. It is also the only known Ghost that has the ability of flight and has sometimes been known to travel through walls.`,
    strength: `Wraiths almost never touch the ground meaning it can’t be tracked by footsteps.`,
    weakness: `Wraiths have a toxic reaction to Salt.`,
    evidence: `EMF Level 5, Spirit Box, DOTS Projector`,
    nameRU: `Мираж`,
    descRU: `Мираж - один из самых опасных видов призраков. Единственный из всех, способный парить, а также проходить сквозь стены.`,
    strengthRU: `Мираж практически никогда не касается земли, а следовательно, не оставляет следов.`,
    weaknessRU: `Соль токсична для Миража.`,
    nameES: `Espectro`,
    descES: `Un Espectro es uno de los Fantasmas más peligrosos. También es el único Fantasma que tiene la habilidad de volar y se conoce que a veces atraviesa paredes.`,
    strengthES: `Un Espectro nunca dejará pisadas rastreables en el suelo.`,
    weaknessES: `Un Espectro tendrá una reacción tóxica en contacto con la Sal.`,
    nameFR: `Spectre`,
    descFR: `Un spectre est un des plus dangereux fantômes que vous pourrez trouver. Il est aussi connu pour être le seul fantôme à pouvoir voler et à avoir parfois été connu pour avoir traverser les murs. `,
    strengthFR: `Les spectres ne toucheront jamais le sol ce qui signifie que vous ne pouvais pas le traquer grâce à ses traces de pas. `,
    weaknessFR: `Les spectre ont aussi une très mauvaise réaction face au sel`,
    nameIT: `Spettro`,
    descIT: `Lo Spettro è uno dei Fantasmi più pericolosi che puoi incontrare. E' l'unico Fantasma conosciuto che ha la capacità di volare ed è stato visto attraversare i muri.`,
    strengthIT: `Lo Spettro non tocca quasi mai il suolo, significa che non può essere rintracciato dai passi.`,
    weaknessIT: `Lo Spettro ha una reazione tossica al sale.`,
  },
  {
    type: 'ghost',
    name: 'Phantom',
    desc: `A Phantom is a Ghost that can possess the living, most commonly summoned by a Ouija Board. It also induces fear into those around it.`,
    strength: `Looking at a Phantom will considerably drop your sanity.`,
    weakness: `Taking a photo of the Phantom will make it temporarily disappear.`,
    evidence: `Spirit Box, Fingerprints, DOTS Projector`,
    nameRU: `Фантом`,
    descRU: `Фантом - призрак, способный вселяться в живых людей, обычно появляется из-за неосторожного использования Доски Уиджи. Вселяет страх в находящихся рядом с ним.`,
    strengthRU: `Один лишь вид Фантома заметно снижает уровень Рассудка.`,
    weaknessRU: `Если сфотографировать Фантома, он исчезнет на некоторое время.`,
    nameES: `Ente`,
    descES: `Un Ente es un Fantasma que puede poseer a los vivos, suele ser invocado mediante un Tablero de Ouija. También induce miedo en aquellas personas que lo rodean.`,
    strengthES: `Mirar a un Ente hará que tu Cordura disminuya considerablemente.`,
    weaknessES: `Fotografiar a un Ente hará que desaparezca temporalmente.`,
    nameFR: `Fantôme`,
    descFR: `Un fantôme est un type d'esprit qui peut posséder un vivant, plus souvent invoquer par un table Ouija. Il induit la peur au personne à ses alentours. `,
    strengthFR: `Regarder un fantôme droit dans les yeux vous fera considérablement baisser votre santé mentale. `,
    weaknessFR: `Prendre une photo du fantôme va le faire temporairement disparaître. `,
    nameIT: `Phantom`,
    descIT: `Il Phantom è un Fantasma che può possedere i vivi, solitamente viene invocato da una Tavola Ouija. Induce paura in coloro che si trovano intorno ad esso.`,
    strengthIT: `Guardare il Phantom ti farà perdere una quantità considerevole di Sanità Mentale.`,
    weaknessIT: `Scattare una foto al Phantom lo farà scomparire temporaneamente.`,
  },
  {
    type: 'ghost',
    name: 'Poltergeist',
    desc: `One of the most famous Ghosts, a Poltergeist, also known as a noisy ghost can manipulate objects around it to spread fear into it’s victims.`,
    strength: `A Poltergeist can throw huge amounts of objects at once.`,
    weakness: `A Poltergeist is almost ineffective in an empty room.`,
    evidence: `Ghost Writing, Spirit Box, Fingerptints`,
    nameRU: `Полтергейст`,
    descRU: `Один из самых известных призраков. Может шуметь и взаимодействовать с окружающими предметами, вселяя страх в своих жертв.`,
    strengthRU: `Полтергейст может швырять много предметов одновременно.`,
    weaknessRU: `Практически безоружен в пустой комнате.`,
    nameES: `Poltergeist`,
    descES: `Uno de los Fantasmas más famosos, el Poltergeist, también conocido por ser uno de los más ruidosos. Puede manipular los objetos que le rodean infundiendo así miedo en sus víctimas.`,
    strengthES: `Un Poltergeist puede lanzar muchos objetos a la vez.`,
    weaknessES: `Un Poltergeist es prácticamente inútil en una habitación vacía.`,
    nameFR: `Poltergeist`,
    descFR: `Un des esprits les plus connus, le poltergeist, aussi connu pour être un esprit très bruillant qui peut manipuler des objet afin d'effrayer ses victimes. `,
    strengthFR: `Le poltergeist peut balancer d'énorme quantité d'objets à la fois. `,
    weaknessFR: `Le poltergeist est donc très insignifiant dans une pièce vide`,
    nameIT: `Poltergeist`,
    descIT: `Uno dei Fantasmi più famosi, il Poltergeist,noto anche come Fantasma rumoroso, può manipolare gli oggetti intorno a seper diffondere paura nelle sue vittime.`,
    strengthIT: `Il Poltergeist può lanciare una grossa quantità di oggetti in una sola volta.`,
    weaknessIT: `Il Poltergeist è quasi inefficace in una stanza vuota.`,
  },
  {
    type: 'ghost',
    name: 'Banshee',
    desc: `A Banshee is a natural hunter and will attack anything. It has been known to stalk it’s prey one at a time until making it’s kill.`,
    strength: `A Banshee will only target one person at a time.`,
    weakness: `Banshees fear the Crucifix and will be less aggressive when near one.`,
    evidence: `Ghost Orb, Fingerprints, DOTS Projector`,
    nameRU: `Банши`,
    descRU: `Банши - природный хищник и может атаковать кого угодно. Известно, что банши будет преследовать избранную жертву до тех пор, пока не убьёт.`,
    strengthRU: `Фокусируются на одном конкретном человеке.`,
    weaknessRU: `Боятся распятия и будут менее агрессивны, если оно оставлено поблизости.`,
    nameES: `Banshee`,
    descES: `La Banshee es una depredadora natural que atacará a cualquier cosa. Se conoce que acecha a sus presas y les mata de una en una.`,
    strengthES: `La Banshee solo podrá marcar a un jugador a la vez.`,
    weaknessES: `Las Banshees temen el Crucifijo haciendo que sean menos agresivas si se encuentran cerca de uno.`,
    nameFR: `Banshee`,
    descFR: `Un Banshee est un chasseur naturel et va attaquer n'importe qui. Il est connu pour suivre ses proies une à une jusqu'à ce qu'il le tue. `,
    strengthFR: `Un Banshee va uniquement prendre en chasse une personne à la fois. `,
    weaknessFR: `Les Banshee ont très peur d'un crucifix et vont donc être moins aggresif quand ils seront proche d'un crucifix. `,
    nameIT: `Banshee`,
    descIT: `La Banshee è una predatrice di natura che attacca qualsiasi cosa. E' risaputo che perseguita le prede una alla volta fino ad ucciderle.`,
    strengthIT: `La Banshee attacca solo una persona alla volta.`,
    weaknessIT: `La Banshee teme il Crocifisso e sarà meno aggressiva vicino a uno di essi.`,
  },
  {
    type: 'ghost',
    name: 'Jinn',
    desc: `A Jinn is a territorial Ghost that will attack when threatened. It has also been known to be able to travel at significant speed.`,
    strength: `A Jinn will travel at a faster speed if it’s victim is far away.`,
    weakness: `Turning off the locations power source will prevent the Jinn from using it’s ability.`,
    evidence: `EMF Level 5, Freezing Temperatures, Fingerprints`,
    nameRU: `Джинн`,
    descRU: `Джинн - призрак, охраняющий свою территорию и атакующий в случае опасности. Известно, что джинны могут перемещаться с высокой скоростью.`,
    strengthRU: `Джинн будет перемещаться быстрее, если жертва далеко.`,
    weaknessRU: `Если отключить электричество, Джинн не сможет использовать свои способности.`,
    nameES: `Jinn`,
    descES: `Un Jinn es un Fantasma territorial que atacará cuando se sienta amenazado. También son conocidos por moverse a gran velocidad.`,
    strengthES: `Un Jinn viajará más rápido cuanto mayor sea la distancia entre él y su víctima.`,
    weaknessES: `Cuando el cuadro eléctrivo esté apagado un Jinn no podrá usar su habilidad.`,
    nameFR: `Djinn`,
    descFR: `Un djinn est un esprit très territorial qui va attaquer lorsqu'il sera menacé. Il est aussi connu pour être capable d'aller à une vitesse assez conséquente.`,
    strengthFR: `Un djinn sera encore plus rapide si la victime est loin par rapport à lui. `,
    weaknessFR: `Éteindre les sources d'alimentations de l'emplacement où il se trouve l'empêchera d'utiliser sa capacité. `,
    nameIT: `Jinn`,
    descIT: `Il Jinn è un Fantasma territoriale che attacca quando si sente minacciato. E' noto per essere in grado di muoversi a velocità notevole.`,
    strengthIT: `Il Jinn si muoverà più velocemente se la vittima è lontana.`,
    weaknessIT: `Spegnere il quadro elettrico impedirà al Jinn di utilizzare la sua abilità.`,
  },
  {
    type: 'ghost',
    name: 'Mare',
    desc: `A Mare is the source of all nightmares, making it most powerful in the dark.`,
    strength: `A Mare will have an increased chance to attack in the dark.`,
    weakness: `Turning the lights on around the Mare will lower it’s chance to attack.`,
    evidence: `Ghost Orb, Ghost Writing, Spirit Box`,
    nameRU: `Мара`,
    descRU: `Мара - источник всех кошмарных сновидений и наиболее сильна в темноте.`,
    strengthRU: `Мара более агрессивна под покровом темноты.`,
    weaknessRU: `В освещённом помещении шанс быть атакованным Марой меньше.`,
    nameES: `Pesadilla`,
    descES: `Una Pesadilla es un Fantasma terrorífico, conocido por ser el culpable de todos los malos sueños, se puede así inferir que es muy poderoso en la oscuridad.`,
    strengthES: `Una pesadilla tendrá más probabilidades de atacarte si te encuentras a oscuras.`,
    weaknessES: `Encender las luces hará que una Pesadilla tenga menos probabilidades de atacarte.`,
    nameFR: `Cauchemar`,
    descFR: `Le cauchemar est la source de tout les mauvais rêves, le rendant plus fort dans le noir. `,
    strengthFR: `Le cauchemar a une chance accrue d'attaquer dans le noir. `,
    weaknessFR: `Allumez les lumières autour du cauchemar va le rendre moins aggresif. `,
    nameIT: `Mare`,
    descIT: `Il Mare è la fonte di tutti gli incubi, che lo rendono più potente al buio.`,
    strengthIT: `Il Mare ha una maggiore probabilità di attaccare al buio.`,
    weaknessIT: `Accendere le luci intorno al Mare diminuisce le probabilità che attacchi.`,
  },
  {
    type: 'ghost',
    name: 'Revenant',
    desc: `A Revenant is a slow but violent Ghost that will attack indiscriminately. It has been rumored to travel at a significantly high speed when hunting.`,
    strength: `A Revenant will travel at a significantly faster speed when hunting a victim`,
    weakness: `Hiding from the Revenant will cause it to move very slowly.`,
    evidence: `Ghost Orb, Ghost Writing, Freezing Temperatures`,
    nameRU: `Ревенант`,
    descRU: `Ревенант - медлительный, но жестокий призрак, который будет атаковать без разбору. Говорят, он двигается быстрее, когда выходит на охоту.`,
    strengthRU: `Ревенант будет передвигаться быстрее, преследуя жертву.`,
    weaknessRU: `Если спрятаться от Ревенанта, он снизит скорость передвижения.`,
    nameES: `Revenant`,
    descES: `Un Revenant es un Fantasma lento pero muy violento que atacará indiscriminadamente a cualquiera. Se rumorea que puede moverse a gran velocidad.`,
    strengthES: `Un Revenant se desplaza más rápido si va tras su presa.`,
    weaknessES: `Esconderte de un Revenant hará que se mueva muy lento.`,
    nameFR: `Revenant`,
    descFR: `Le revenant est un plus lent mais un plus violent esprit qui va attaquer indistinctement. Il y a des rumeurs sur le fait qu'il se déplace à une vitesse élevé quand il chasse. `,
    strengthFR: `Un revenant va se déplacer à une vitesse élevé quand il chassera une victime. `,
    weaknessFR: `Se cacher d'un revenant causera un déplacement ralenti du revenant. `,
    nameIT: `Revenant`,
    descIT: `Il Revenant è un Fantasma lento ma violento che attacca indiscriminatamente. Si dice che si muova ad una velocità molto elevata quando da la caccia.`,
    strengthIT: `Il Revenant si muove ad una velocità molto elevata quando caccia una vittima.`,
    weaknessIT: `Nascondersi dal Revenant lo farà muovere molto lentamente.`,
  },
  {
    type: 'ghost',
    name: 'Shade',
    desc: `A Shade is known to be a Shy Ghost. There is evidence that a Shade will stop all paranormal activity if there are multiple people nearby.`,
    strength: `Being shy means the ghost will be harder to find.`,
    weakness: `The Ghost will not enter hunting mode if there are multiply people nearby.`,
    evidence: ` EMF 5, Ghost Writing, Freezing Temperatures`,
    nameRU: `Тень`,
    descRU: `Тень - застенчивый призрак. Похоже, что Тень прекращает любую деятельность, если рядом несколько человек.`,
    strengthRU: `Поскольку Тень застенчива, найти её будет нелегко.`,
    weaknessRU: `Тень не станет начинать охоту, если рядом сразу несколько человек.`,
    nameES: `Sombra`,
    descES: `Una Sombra es bien conocida por ser un Fantasma tímido. Existe la evidencia de que una Sombra no generará actividad paranormal si hay varias personas cerca.`,
    strengthES: `Una Sombra es muy difícil de encontrar ya que es muy tímida.`,
    weaknessES: `Una Sombra no atacará si varias personas se encuentran juntas.`,
    nameFR: `Ombre`,
    descFR: `L'ombre est connue pour être un esprit timide. Il y a des chances pour que, s'il y a beaucoup de monde, elle arrête toute activité paranormal. `,
    strengthFR: `L'ombre étant timide, elle sera plus compliqué à trouvé. `,
    weaknessFR: `L'ombre ne se mettra pas en chasse s'il y a plus de une personne à proximité. `,
    nameIT: `Ombra`,
    descIT: `L'Ombra è noto per essere un Fantasma timido. Alcune prove dimostrano che l'Ombra interrompe tutte le attività paranormali se ci sono più persone nelle vicinanze.`,
    strengthIT: `Essendo timido, il Fantasma sarà più difficile da trovare.`,
    weaknessIT: `Il Fantasma non darà la caccia se vi sono più persone nelle vicinanze.`,
  },
  {
    type: 'ghost',
    name: 'Demon',
    desc: `A Demon is one of the worst Ghosts you can encounter. It has been known to attack without a reason.`,
    strength: `Demons will attack more often than any other Ghost.`,
    weakness: `Asking a Demon successful questions on the Ouija Board won’t lower the user's sanity.`,
    evidence: `Freezing Temperatures, Ghost Writing, Fingerprints`,
    nameRU: `Демон`,
    descRU: `Демон - один из самых жестоких призраков. Известно, что он склонен атаковать совершенно без причины.`,
    strengthRU: `Демон будет атаковать чаще остальных призраков.`,
    weaknessRU: `Если задавать Демону успешные вопросы через Доску Уиджи, ваш рассудок не будет снижаться.`,
    nameES: `Demonio`,
    descES: `Un Demonio es uno de los peores Fantasmas que te puedes encontrar. Son conocidos por atacar sin ninguna razón aparente.`,
    strengthES: `Los Demonios atacarán de manera más frecuente que otros Fantasmas.`,
    weaknessES: `Hacer preguntas con el Tablero de Ouija hará que la Cordura no disminuya.`,
    nameFR: `Démon`,
    descFR: `Un démon est l'un des pires esprit que vous pouvez rencontrer. Il est connu pour attaquer sans raison. `,
    strengthFR: `Le démon attaquera plus que n'importe quel autre esprit. `,
    weaknessFR: `Une réponse du revenant ne diminuera pas la santé mentale du chasseur si une table Ouija est utilisé. `,
    nameIT: `Demone`,
    descIT: `Il Demone è uno dei Fantasmi peggiori che si possano incontrare. E' risaputo che attacchi senza un motivo.`,
    strengthIT: `Il Demone attacca più spesso di qualsiasi altro Fantasma.`,
    weaknessIT: `Porre a un Demone le domande giuste con la Tavola Ouija non ti farà perdere Sanità Mentale.`,
  },
  {
    type: 'ghost',
    name: 'Yurei',
    desc: `A Yurei is a ghost that has returned to the physical world, usually for the purpose of revenge or hatred.`,
    strength: `Yurei’s have been known to have a stronger effect on people’s sanity.`,
    weakness: `Smudging the Yurei’s room will cause it to not wander around the location for a long time.`,
    evidence: `Ghost Orbs, Freezing Temperatures, DOTS Projector`,
    nameRU: `Юрэй`,
    descRU: `Как правило, Юрэй возвращается в мир живых ради мести или из-за ненависти.`,
    strengthRU: `Юрэй влияет на ваш рассудок сильнее обычного.`,
    weaknessRU: `Если зажечь Благовоние в комнате с Юрэй, призрак не сможет перемещаться долгое время.`,
    nameES: `Yurei`,
    descES: `Un Yurei es un Fantasma que ha vuelto al plano físico, normalmente ansiando una venganza o lleno de odio.`,
    strengthES: `Los Yureis tienen un gran impacto en la Cordura de los individiuos.`,
    weaknessES: `Usar Varillas de Incienso en la habitación de un Yurei hará que no se paseé por ahí durante un gran periodo de tiempo.`,
    nameFR: `Yurei`,
    descFR: `Un Yurei est un esprit qui est revenu dans le monde physique, souvent pour une revanche ou par haine. `,
    strengthFR: `Une Yurei est connue pour avoir un effet sur les santés mentales. `,
    weaknessFR: `Mettre de l'encens dans la salle du Yurei l'empêchera de rôder autour durant un long moment. `,
    nameIT: `Yurei`,
    descIT: `Lo Yurei è un Fantasma che è ritornato nel mondo fisico, solitamente per vendetta o per odio.`,
    strengthIT: `Lo Yurei ha un forte effetto sulla Sanità Mentale delle persone.`,
    weaknessIT: `Purificare la stanza di uno Yurei con l'Incenso gli impedirà di vagare nei dintorni per un bel po’.`,
  },
  {
    type: 'ghost',
    name: 'Oni',
    desc: `Onis are a cousin to the Demon and possess extreme strength. There have been rumors that they become more active around their prey.`,
    strength: `Onis are more active when people are nearby and have been seen moving objects at great speed.`,
    weakness: `Being more active will make the Oni easier to find and identify.`,
    evidence: ` EMF Level 5, Freezing Temperature, DOTS Projector`,
    nameRU: `Óни`,
    descRU: `Óни родственны Демону и невероятно сильны. Говорят, они становятся более активны, если жертва находится рядом.`,
    strengthRU: `Óни более активны в присутствии людей и могут перемещать предметы с высокой скоростью.`,
    weaknessRU: `Поскольку Óни очень активны, их легко обнаружить и распознать.`,
    nameES: `Oni`,
    descES: `Un Oni es un primo hermano de un Demonio y poseen una fuerza abrumadroa. Hay rumores de que se vuelven más activos alrededor de su presa.`,
    strengthES: `Los Oni son más activos cuanta más gente haya alrededor de ellos y tienen la capacidad de lanzar objetos a grandes velocidades.`,
    weaknessES: `Los Oni al ser más activos, son fáciles de encontrar e identificar.`,
    nameFR: `Oni`,
    descFR: `Les Onis sont cousins des démons et possèdent par conséquent une force extrême. Il y a des rumeur sur le fait qu'il serait plus actif au alentours de leur proie. `,
    strengthFR: `Les Onis sont plus actifs quand une personne est proche et a vu un objet bougé par l'esprit. `,
    weaknessFR: `Étant plus actif, le Oni sera plus facile à trouver et à identifier. `,
    nameIT: `Oni`,
    descIT: `L'Oni è un cugino del Demone e possiede una forza estrema. Dicono diventino più attivi intorno alla loro preda.`,
    strengthIT: `L'Oni è più attivo quando ci sono persone nelle vicinanze, sono stati anche visti oggetti muoversi a grande velocità.`,
    weaknessIT: `Essendo molto attivo, è più facile da trovare e identificare.`,
  },
  {
    type: 'ghost',
    name: 'Hantu',
    desc: `A rare ghost that can be found in hot climates. They are known to attack more often in cold weather`,
    strength: `Moves faster in colder areas`,
    weakness: `Moves slower in warmer areas`,
    evidence: `Fingerprints, Ghost Orb, Freezing Temperatures`,
    nameRU: `Ханту`,
    descRU: `Редкое привидение, которое можно встретить в жарком климате. Известно, что они чаще атакуют в холодную погоду.`,
    strengthRU: `Двигается быстрее в более холодных местах.`,
    weaknessRU: `В более теплых местах передвигается медленнее.`,
    nameES: `Hantu`,
    descES: `
    Un fantasma raro que se puede encontrar en climas cálidos. Se sabe que atacan con más frecuencia en climas fríos.`,
    strengthES: `Se mueve más rápido en áreas más frías.`,
    weaknessES: `Se mueve más lento en áreas más cálidas.`,
    nameFR: `Hantu`,
    descFR: `Un fantôme rare que l'on peut trouver dans les climats chauds. Ils sont connus pour attaquer plus souvent par temps froid`,
    strengthFR: `Se déplace plus rapidement dans les zones plus froides`,
    weaknessFR: `Se déplace plus lentement dans les zones plus chaudes`,
    nameIT: `Hantu`,
    descIT: `Un raro fantasma che può essere trovato nei climi caldi. Sono noti per attaccare più spesso quando fa freddo.`,
    strengthIT: `Si muove più velocemente nelle zone più fredde`,
    weaknessIT: `Si muove più lentamente nelle zone più calde`,
  },
  {
    type: 'ghost',
    name: 'Yokai',
    desc: `A common type of ghost that is attracted to human voices. They can usually be found haunting family homes.`,
    strength: `Talking near a Yokai will anger it and cause it to attack more often.`,
    weakness: `While hunting, it can only hear voices close to it`,
    evidence: `Ghost Orb, Spirit Box, DOTS Projector`,
    nameRU: `Ёкай`,
    descRU: `Распространенный тип призраков, которых привлекают человеческие голоса. Обычно их можно найти в семейных домах.`,
    strengthRU: `Разговор с ёкаем разозлит его и заставит чаще атаковать.`,
    weaknessRU: `Во время охоты он может слышать только голоса рядом с собой.`,
    nameES: `Yokai`,
    descES: `Un tipo común de fantasma que se siente atraído por las voces humanas. Por lo general, se pueden encontrar en casas familiares inquietantes.`,
    strengthES: `Hablar cerca de un Yokai lo enojará y hará que ataque con más frecuencia.`,
    weaknessES: `Mientras caza, solo puede escuchar voces cercanas a él.`,
    nameFR: `Yokai`,
    descFR: `Un type commun de fantôme qui est attiré par les voix humaines. Ils peuvent généralement être trouvés hantant les maisons familiales.`,
    strengthFR: `Parler près d'un Yokai le mettra en colère et le fera attaquer plus souvent.`,
    weaknessFR: `Pendant la chasse, il ne peut entendre que des voix proches de lui`,
    nameIT: `Yokai`,
    descIT: `Un tipo comune di fantasma che è attratto dalle voci umane. Di solito possono essere trovati infestati da case di famiglia.`,
    strengthIT: `Parlare vicino a uno Yokai lo farà arrabbiare e lo farà attaccare più spesso.`,
    weaknessIT: `Durante la caccia, può sentire solo voci vicine a sé`,
  },
  {
    type: 'ghost',
    name: 'Goryo',
    desc: `A Japanese ghost who's typically an aristocrat who's been martyred for their beliefs`,
    strength: `A Goryo will usually only show itself on camera if there are no people nearby`,
    weakness: `They are rarely seen far from their place of death`,
    evidence: `EMF Level 5, Fingerprints, DOTS Projector`,
    nameRU: `Goryo`,
    descRU: `Японский призрак, кто, как правило, аристократ, который был замучен за свои убеждения`,
    strengthRU: `Goryo обычно только показать себя на камеру, если нет людей поблизости`,
    weaknessRU: `Они редко встречаются далеко от места их смерти`,
    nameES: `Goryo`,
    descES: `Un fantasma japonés que es típicamente un aristócrata que ha sido martirizado por sus creencias`,
    strengthES: `Un Goryo lo general sólo mostrarse en la cámara si no hay gente cercana`,
    weaknessES: `Rara vez son vistos lejos de su lugar de muerte`,
    nameFR: `Goryo`,
    descFR: `Un fantôme japonais qui est généralement un aristocrate qui a été martyrisé pour leurs croyances`,
    strengthFR: `Un Goryo se montrera généralement à la caméra s'il n'y a personne à proximité`,
    weaknessFR: `Ils sont rarement loin de leur lieu de mort`,
    nameIT: `Goryo`,
    descIT: `Un fantasma giapponese che è tipicamente un aristocratico che è stato martirizzato per le loro credenze`,
    strengthIT: `Un Goryo di solito si mostra soltanto sulla macchina fotografica se non ci sono persone vicine`,
    weaknessIT: `Essi si vedono raramente lontano dal luogo del decesso`,
  },
  {
    type: 'ghost',
    name: 'Myling',
    desc: `The lost souls of children who wander the earth trying to get anybody to properly bury them`,
    strength: `Known to be quieter when hunting`,
    weakness: `More frequently make paranormal sounds`,
    evidence: `EMF Level 5, Fingerprints, Ghost Writing`,
    nameRU: `утбурд`,
    descRU: `Потерянные души детей, которые бродят по земле, пытаясь получить кто-нибудь, чтобы правильно их похоронить`,
    strengthRU: `Известный быть спокойнее, когда охота`,
    weaknessRU: `Чаще всего делают паранормальные звуки`,
    nameES: `Myling`,
    descES: `Las almas perdidas de los niños que deambulan por la tierra tratando de conseguir a nadie para enterrarlos adecuadamente`,
    strengthES: `Se sabe que es más silencioso cuando la caza`,
    weaknessES: `Con más frecuencia que los sonidos paranormales`,
    nameFR: `Myling`,
    descFR: `Les âmes perdues des enfants qui errent la terre en essayant de trouver quelqu'un d'enterrer correctement les`,
    strengthFR: `Connu pour être plus tranquille quand la chasse`,
    weaknessFR: `Le plus souvent des sons paranormal`,
    nameIT: `Myling`,
    descIT: `Le anime perdute di bambini che vagano la terra cercando di arrivare a chiunque di correttamente seppellirli`,
    strengthIT: `Conosciuto per essere più tranquillo, quando la caccia`,
    weaknessIT: `Più frequentemente rendere i suoni paranormali`,
  },
  {
    type: 'ghost',
    name: 'Onryo',
    desc: `The Onryo is often referred to as "The Wrathful Spirit." It steals souls from dying victims' bodies to seek revenge. This ghost has been known to fear any form of fire, and will do anything to be far from it.`,
    strength: `Extinguishing a flame can cause an Onryo to attack.`,
    weakness: `When threatened, this ghost will be less likely to hunt.`,
    evidence: `Spirit Box, Ghost Orb, Freezing Temperatures`,
    nameRU: `Onryo`,
    descRU: `Онрыо часто называют «германным духом». Он крадет души от умирающих органов жертв, чтобы искать месть. Этот призрак был известен, что опасается любой формы огня, и сделает все, чтобы быть далеко от него.`,
    strengthRU: `Тушение пламени может вызвать атаку на onryo.`,
    weaknessRU: `При угрозе этот призрак будет меньше шансов на охоту.`,
    nameES: `Onryo`,
    descES: `El Onryo a menudo se conoce como "el espíritu iracundo". Roba las almas de los cuerpos de las víctimas muriendo para buscar venganza. Se sabe que este fantasma teme cualquier forma de fuego, y hará cualquier cosa para estar lejos de ella.`,
    strengthES: `La extinción de una llama puede hacer que un Onryo ataque.`,
    weaknessES: `Cuando se amenaza, este fantasma será menos probable que cazan.`,
    nameFR: `Onryo`,
    descFR: `L'Onryo est souvent appelé "l'esprit courroucé". Il vole des âmes de mourir les corps des victimes de se venger. Ce fantôme a été connu pour craindre toute forme de feu et fera n'importe quoi pour être loin de celle-ci.`,
    strengthFR: `L'extinction d'une flamme peut provoquer une attaque d'un onryo.`,
    weaknessFR: `Lorsqu'elle est menacée, ce fantôme sera moins susceptible de chasser.`,
    nameIT: `Onryo`,
    descIT: `L'onryo è spesso indicato come "lo spirito irato". Ruba le anime dai corpi delle vittime morenti a cercare vendetta. Questo fantasma è noto per temere qualsiasi forma di fuoco e farà qualsiasi cosa per essere lontani da esso.`,
    strengthIT: `Estinguere una fiamma può causare attaccare un onryo.`,
    weaknessIT: `Quando minacciato, questo fantasma sarà meno propenso a cacciare.`,
  },
  {
    type: 'ghost',
    name: 'The Twins',
    desc: `These ghosts have been reported to mimic each other's actions. They alternate their attacks to confuse their prey.`,
    strength: `Either Twin can be angered and initiate an attack on their prey.`,
    weakness: `The Twins will often interact with the environment at the same time.`,
    evidence: `EMF Level 5, Spirit Box, Freezing Temperatures`,
    nameRU: `Близнецы`,
    descRU: `Эти призраки сообщают, что имитируют действия друг друга. Они чередуют свои атаки, чтобы запутать свою добычу.`,
    strengthRU: `Либо Twin может быть разогнан и инициирует атаку на их добычу.`,
    weaknessRU: `Близнецы часто взаимодействуют с окружающей средой одновременно.`,
    nameES: `Los gemelos`,
    descES: `Se ha informado que estos fantasmas imitan las acciones de cada uno. Alternan sus ataques para confundir a su presa.`,
    strengthES: `Cualquiera de los dos se puede enfurecerse e iniciar un ataque a su presa.`,
    weaknessES: `Los gemelos a menudo interactuarán con el medio ambiente al mismo tiempo.`,
    nameFR: `Les jumeaux`,
    descFR: `Ces fantômes ont été signalés à imiter les actions de chacun. Ils alternent leurs attaques pour confondre leur proie.`,
    strengthFR: `Soit Twin peut être en colère et initier une attaque sur leur proie.`,
    weaknessFR: `Les jumeaux interagiront souvent avec l'environnement en même temps.`,
    nameIT: `I gemelli`,
    descIT: `Questi fantasmi sono stati segnalati per imitare le azioni dell'altro. Si alternano i loro attacchi per confondere la loro preda.`,
    strengthIT: `O due volte può essere arrabbiato e avviare un attacco alla loro preda.`,
    weaknessIT: `O due volte può essere arrabbiato e avviare un attacco alla loro preda.`,
  },
  {
    type: 'ghost',
    name: 'Obake',
    desc: `Obake are terrifying shape-shifters, capable of taking on many forms. They have been seen taking on humanoid shapes to attract their prey.`,
    strength: `Rarely leaves a trace when interacting with the environment.`,
    weakness: `Sometimes leaves behind unique evidence.`,
    evidence: `EMF Level 5, Fingerprints, Ghost Orb`,
    nameRU: `Obake`,
    descRU: `Okoke ужасают фигуристы, способные принимать во многих формах. Их видно, что принимает гуманоидные формы, чтобы привлечь свою добычу.`,
    strengthRU: `Редко оставляет след при взаимодействии с окружающей средой.`,
    weaknessRU: `Иногда оставляет уникальные доказательства.`,
    nameES: `Obake`,
    descES: `El Obake son turqueros aterradores, capaz de tomar muchas formas. Se les ha visto tomar formas humanoides para atraer a su presa.`,
    strengthES: `Rara vez deja un rastro al interactuar con el medio ambiente.`,
    weaknessES: `A veces deja detrás de evidencia única.`,
    nameFR: `Obake`,
    descFR: `Les obakes sont terrifiants-shifters, capables de prendre de nombreuses formes. On leur a été vu en prenant des formes humanoïdes pour attirer leur proie.`,
    strengthFR: `Laisse rarement une trace lorsque vous interagissez avec l'environnement.`,
    weaknessFR: `Part parfois derrière des preuves uniques.`,
    nameIT: `Obake`,
    descIT: `Gli Obake sono terrificanti Shape-Shiplers, in grado di assumere molte forme. Sono stati visti assumere forme umanoidi per attirare la loro preda.`,
    strengthIT: `Raramente lascia una traccia quando interagire con l'ambiente.`,
    weaknessIT: `A volte lascia alle prove uniche.`,
  },
  {
    type: 'ghost',
    name: 'Raiju',
    desc: `A Raiju is a demon that thrives on electrical current. While generally calm, they can become agitated when overwhelmed with power.`,
    strength: `Moves faster near electrical devices.`,
    weakness: `Constantly disrupt electronic equipment.`,
    evidence: `EMF Level 5, Ghost Orb, DOTS Projector`,
    nameRU: `Raiju`,
    descRU: `Райджу - это демон, который процветает на электрический ток. Хотя вообще спокойно, они могут взволнованы, когда он перегружен с силой.`,
    strengthRU: `Перемещает быстрее возле электрических устройств.`,
    weaknessRU: `Постоянно нарушать электронное оборудование.`,
    nameES: `Raiju`,
    descES: `Un Raiju es un demonio que prospera en la corriente eléctrica. Mientras que generalmente se calma, pueden agitarse cuando se abruman con el poder.`,
    strengthES: `Se mueve más rápido cerca de dispositivos eléctricos.`,
    weaknessES: `Altera constantemente el equipo electrónico.`,
    nameFR: `Raiju`,
    descFR: `Un Raiju est un démon qui se développe sur le courant électrique. Bien que généralement calme, ils peuvent être agités lorsqu'ils sont submergés de puissance.`,
    strengthFR: `Déplace plus rapidement les appareils électriques.`,
    weaknessFR: `Perturber constamment l'équipement électronique.`,
    nameIT: `Raiju`,
    descIT: `Un raiju è un demone che prospera sulla corrente elettrica. Mentre generalmente calmi, possono diventare agitati quando sopraffatti dal potere.`,
    strengthIT: `Si muove più velocemente vicino ai dispositivi elettrici.`,
    weaknessIT: `Interrompere costantemente le apparecchiature elettroniche.`,
  },
  {
    type: 'tool',
    name: `Smudging`,
    desc: `This has always been one of the main ways to weaken the more common ghosts. To do this you will need to grab some Smudge Sticks and burn it near the Ghost.`,
    nameRU: `Благовоние`,
    descRU: `Благовоние с давних времен было основным способом ослабить большинство призраков. Возьмите несколько Благовоний и подожгите рядом с Призраком.`,
    nameES: `Incienso`,
    descES: `Esta ha sido durante siglos la manera convencional de calmar a un fanstasma. Enciende las Varillas de Incienso cerca del fantasma para debilitarlo.`,
    nameFR: `Les Encens`,
    descFR: `C'est toujours un moyen de réveiller les plus communs esprits. Pour ça, vous aurez besoin de prendre quelque bâtons d'encens et les allumer près de l'esprit. `,
    nameIT: `Incenso`,
    descIT: `E' da sempre uno dei principali modi per indebolire i Fantasmi più comuni. Per usarlo correttamente è necessario prendere alcuni bastoni di Incenso e bruciarli nei pressi del Fantasma.`,
  },
  {
    type: 'tool',
    name: `Ouija Board`,
    desc: `The most common way of accidentally summoning a ghost is with a Ouija Board so you may come across these during your investigations. Be careful if you choose to use it as they have been known to lower your sanity. To use one, activate it and then ask a question with your voice.`,
    nameRU: `Доска Уиджи`,
    descRU: `Поскольку призраки часто возникают в результате неосторожного использования спиритической доски, вы наверняка найдёте Доску Уиджи во время расследования. Будьте осторожны, так как использование доски снижает ваш уровень Рассудка. Для использования активируйте и задавайте вопросы вслух.`,
    nameES: `Tablero de Ouija`,
    descES: `La manera tradicional de invocar un Fantasma por error es con el Tablero de Ouija que puedes encontrar durante tus investigaciones. Ten cuidado si eliges utilizarlo ya que disminuye considerablemente tu Cordura. Para usarla sólo debes activarla y hacer una pregunta.`,
    nameFR: `La table ouija`,
    descFR: `Le moyen le plus commun d'invoquer un esprit est avec une table Ouija donc vous devrez venir avec elle durant vos investigations. Attention si vous décidez de l'utiliser car elle est connu pour baisser la santé mentale. Pour en utiliser une, activez la et ensuite posez des questions avec votre voix. `,
    nameIT: `Tavola Ouija`,
    descIT: `Il modo più comune di invocare accidentalmente un Fantasmaè con la Tavola Ouija, potresti imbatterti in un' apparizione durante le indagini. Fai attenzione se scegli di usarla, in quanto è noto che faccia perdere Sanità Mentale. Per utilizzarne una, attivala e poni una domanda con la tua voce.`,
  },
  {
    type: 'tool',
    name: `EMF Level 5`,
    desc: `Some Ghosts will leave EMF traces near them that will show up on an EMF Reader as level 5.`,
    nameRU: `Детектор ЭМП`,
    descRU: `Присутствие некоторых призраков вызывает электромагнитные колебания. Если призрак рядом, на датчике отобразится 5 уровень.`,
    nameES: `EMF Nivel 5`,
    descES: `Algunos Fantasmas dejan rastros de EMF allá por donde pasan lo que dará una señal de EMF Nivel 5 en el detector.`,
    nameFR: `L'EMF niveau 5`,
    descFR: `Quelques esprits vont laisser quelques traces EMF près d'eux ce qui va vous activer votre analyseur EMF au niveau 5`,
    nameIT: `EMF Livello 5`,
    descIT: `Alcuni Fantasmi lasceranno tracce EMF vicino a loro che verranno visualizzate su di un lettore EMF come livello 5.`,
  },
  {
    type: 'tool',
    name: `Spirit Box`,
    desc: `Only certain ghosts will talk through a Spirit Box when asked a question with your voice. Make sure the lights are off.`,
    nameRU: `Радиоприёмник`,
    descRU: `Лишь некоторые виды призраков будут отвечать на вопросы при помощи радиоприёмника. Не забудьте выключить свет.`,
    nameES: `Spirit Box`,
    descES: `Algunos Fantasmas se comunicarán contigo a través de la Spirit Box cuando formules una pregunta. Las luces deberán estar apagadas.`,
    nameFR: `Spirit Box`,
    descFR: `Seulement certains esprits vont parler à travers la Spirit Box quand vous poserez une question avec votre voix. Assurez vous que les lumières sont éteintes. `,
    nameIT: `Spirit Box`,
    descIT: `Solo alcuni Fantasmi parleranno attraverso una Spirit Box quando viene posta una domanda. Assicurati che le luci siano spente.`,
  },
  {
    type: 'tool',
    name: `Freezing Temperatures`,
    desc: `All ghosts make areas cold however some ghosts have been known to drop temperatures even further.`,
    nameRU: `Минусовая температура`,
    descRU: `Присутствие призраков всегда снижает температуру, но некоторые способны понижать температуру еще сильнее.`,
    nameES: `Temperaturas bajo cero`,
    descES: `Todos los Fantasmas hacen que disminuya la temperatura ambiente, sin embargo, algunos la disminuyen considerablemente más.`,
    nameFR: `Températures froides`,
    descFR: `Touts les esprits rendent leur endroit froids cependant quelques esprits sont connus pour faire baisser la température encore plus basse. `,
    nameIT: `Temperature di Congelamento`,
    descIT: `Tutti i Fantasmi rendono le zone più fredde, tuttavia alcuni Fantasmi sono noti per far calare ulteriormente la temperatura.`,
  },
  {
    type: 'tool',
    name: `Fingerprints`,
    desc: `Some Ghosts have been known to leave fingerprints on doors, windows and light switches. This will show up with a UV Light.`,
    nameRU: `Отпечатки`,
    descRU: `Некоторые призраки оставляют отпечатки рук на дверях, окнах и выключателях. УФ-фонарик позволит это заметить.`,
    nameES: `Huellas dactilares`,
    descES: `Algunos Fantasmas dejan huellas en las puertas, ventanas e interruptores de luz al interactuar con ellos. Estas huellas se podrán ver con luz ultravioleta.`,
    nameFR: `Des traces d'empreintes`,
    descFR: `Quelques esprits sont connus pour laisser des traces sur les portes, les fenêtres et les interrupteurs. Cela va être révélé grâce à une lampe UV. `,
    nameIT: `Impronte Digitali`,
    descIT: `E' risaputo che alcuni Fantasmi lasciano impronte su porte, finestre e interruttori. Esse verranno visualizzate con una luce UV.`,
  },
  {
    type: 'tool',
    name: `Ghost Orb`,
    desc: `The classic paranormal evidence however not all ghosts have one. This will be visible on a camera.`,
    nameRU: `Призрачный огонёк`,
    descRU: `Классическое явление, напоминающее светлячка, но не все призраки проявляются таким образом. Огонёк виден на видеокамере.`,
    nameES: `Orbes`,
    descES: `Las clásica evidencia paranormal, aunque, algunos Fantasmas no generan estos Orbes. Serán visibles en una cámara de vídeo como un flash redondo y luminoso en movimiento.`,
    nameFR: `Des orbes fantomatiques`,
    descFR: `L'évidence classique cependant pas tout les esprits en ont. Cela sera visible sur une caméra. `,
    nameIT: `Sfera di Luce`,
    descIT: `Classica prova del paranormale, tuttavia, non tutti i Fantasmi ne hanno una. Sarà visibile solo con una videocamera.`,
  },
  {
    type: 'tool',
    name: `Ghost Writing Book`,
    desc: `Some Ghosts are able to write inside this book if placed nearby. Paranormal investigators started using pen and paper as an alternative form of communication to the Spirit Box. It was later discovered that only certain types of Ghosts will write.`,
    nameRU: `Блокнот`,
    descRU: `Исследователи паранормальных явлений начали использовать письмо на бумаге как альтернативный метод коммуникации с призраками. Но было обнаружено, что не все призраки будут общаться подобным способом.`,
    nameES: `Libro de escritura fantasma`,
    descES: `Algunos Fantasmas pueden escribir en este libro si se colocan cerca de ellos. Los investigadores comenzaron a usar boli y papel como una forma alternativa de comunicación a la Spirit Box. Más tarde se descubrió que sólo ciertos tipos de Fantasmas escriben.`,
    nameFR: `L'écrit du fantôme dans le livre`,
    descFR: `Quelques esprits sont capables d'écrire dans ce livre si il est placé près de l'esprit. Les investigateurs de paranormal commencent en utilisant un stylo et un papier comme une forme alternative de communication pour remplacer la Spirit Box. Il a été découvert plus tard que seulement certains types d'esprits vont écrire. `,
    nameIT: `Libro Spiritico`,
    descIT: `Alcuni Fantasmi  sono in grado di scrivere su questo libro se posto nelle vicinanze. Gli investigatori del paranormale iniziarono a utilizzare carta e penna come una forma alternativa di comunicazione alla Spirit Box. Si è poi scoperto che solo alcuni tipi di Fantasmi possono scrivere.`,
  },
  {
    type: 'tool',
    name: `DOTS Projector`,
    desc: `A laser grid of light that can reveal the silhouette of a ghost.`,
    nameRU: `DOTS проекторов`,
    descRU: `Лазерная сетка света, который может выявить силуэт призрака.`,
    nameES: `proyector de DOTS`,
    descES: `Una rejilla de luz láser que puede revelar la silueta de un fantasma.`,
    nameFR: `DOTS projecteur`,
    descFR: `Une grille de laser de lumière qui peut révéler la silhouette d'un fantôme.`,
    nameIT: `proiettore DOTS`,
    descIT: `Una griglia laser di luce che può rivelare la sagoma di un fantasma.`,
  },
  { type: 'evidence' },
  { type: 'timer' },
];

export default cards;
